export const PAPER_PROFESSOR_MY_LIST_REQUEST =
  'PAPER_PROFESSOR_MY_LIST_REQUEST';
export const PAPER_PROFESSOR_MY_LIST_SUCCESS =
  'PAPER_PROFESSOR_MY_LIST_SUCCESS';
export const PAPER_PROFESSOR_MY_LIST_FAIL = 'PAPER_PROFESSOR_MY_LIST_FAIL';
export const PAPER_PROFESSOR_MY_LIST_RESET = 'PAPER_PROFESSOR_MY_LIST_RESET';

export const PAPER_PROFESSOR_UPDATE_REQUEST = 'PAPER_PROFESSOR_UPDATE_REQUEST';
export const PAPER_PROFESSOR_UPDATE_SUCCESS = 'PAPER_PROFESSOR_UPDATE_SUCCESS';
export const PAPER_PROFESSOR_UPDATE_FAIL = 'PAPER_PROFESSOR_UPDATE_FAIL';
export const PAPER_PROFESSOR_UPDATE_RESET = 'PAPER_PROFESSOR_UPDATE_RESET';

export const FILTERED_PAPERS_BY_STATUS_REQUEST =
  'FILTERED_PAPERS_BY_STATUS_REQUEST';
export const FILTERED_PAPERS_BY_STATUS_SUCCESS =
  'FILTERED_PAPERS_BY_STATUS_SUCCESS';
export const FILTERED_PAPERS_BY_STATUS_FAIL = 'FILTERED_PAPERS_BY_STATUS_FAIL';
export const FILTERED_PAPERS_BY_STATUS_RESET =
  'FILTERED_PAPERS_BY_STATUS_RESET';
