export const PAPER_MY_LIST_REQUEST = 'PAPER_MY_LIST_REQUEST';
export const PAPER_MY_LIST_SUCCESS = 'PAPER_MY_LIST_SUCCESS';
export const PAPER_MY_LIST_FAIL = 'PAPER_MY_LIST_FAIL';
export const PAPER_MY_LIST_RESET = 'PAPER_MY_LIST_RESET';

export const PAPER_CREATE_REQUEST = 'PAPER_CREATE_REQUEST';
export const PAPER_CREATE_SUCCESS = 'PAPER_CREATE_SUCCESS';
export const PAPER_CREATE_FAIL = 'PAPER_CREATE_FAIL';
export const PAPER_CREATE_RESET = 'PAPER_CREATE_RESET';

export const PAPER_DETAILS_REQUEST = 'PAPER_DETAILS_REQUEST';
export const PAPER_DETAILS_SUCCESS = 'PAPER_DETAILS_SUCCESS';
export const PAPER_DETAILS_FAIL = 'PAPER_DETAILS_FAIL';

export const PAPER_UPDATE_REQUEST = 'PAPER_UPDATE_REQUEST';
export const PAPER_UPDATE_SUCCESS = 'PAPER_UPDATE_SUCCESS';
export const PAPER_UPDATE_FAIL = 'PAPER_UPDATE_FAIL';
export const PAPER_UPDATE_RESET = 'PAPER_UPDATE_RESET';

export const PAPER_DELETE_REQUEST = 'PAPER_DELETE_REQUEST';
export const PAPER_DELETE_SUCCESS = 'PAPER_DELETE_SUCCESS';
export const PAPER_DELETE_FAIL = 'PAPER_DELETE_FAIL';
